<?php
/**
 * @file
 * Entity reference autofill module.
 */

/**
 * Implements hook_ctools_plugin_directory().
 */
function entityreference_autofill_ctools_plugin_directory($module, $plugin) {
  if ($module == 'entityreference' || $module == 'ctools') {
    return 'plugins/' . $plugin;
  }
}

/**
 * Implements hook_field_update_instance().
 */
function entityreference_autofill_field_update_instance($instance, $prior_instance) {
  if (isset($instance['settings']['behaviors']['autofill'])) {
    // Reset cached autofill settings.
    _entityreference_autofill_get_settings(TRUE);
  }
}

/**
 * Implements hook_field_widget_form_alter().
 */
function entityreference_autofill_field_widget_form_alter(&$element, &$form_state, $context) {
  if (empty($context['instance']['settings']['behaviors']['autofill']['status'])) {
    return;
  }

  // Add ajax callback to element.
  $element['target_id']['#ajax'] = array(
    'callback' => 'entityreference_autofill_form_autofill',
    'wrapper' => 'entityreference-autofill-form',
  );
}

/**
 * Implements hook_field_attach_form().
 */
function entityreference_autofill_field_attach_form($entity_type, $entity, &$form, &$form_state, $langcode) {
  // Get info about current entity.
  list(, , $bundle) = entity_extract_ids($entity_type, $entity);

  // Get array of fields that have enabled autofill.
  $autofill_settings = _entityreference_autofill_get_settings();

  // No autofill references in this bundle.
  if (empty($autofill_settings[$entity_type][$bundle])) {
    return;
  }

  // Add ajax wrapper around form.
  $form['#prefix'] = '<div id="entityreference-autofill-form">';
  $form['#suffix'] = '</div>';

  // Load settings from form_state.
  $autofill_bundle_settings = $autofill_settings[$entity_type][$bundle];

  if (isset($form_state['triggering_element']['#ajax'])) {
    // If an AJAX-call triggered this request,
    // use the triggering field's settings to autofill.
    $reference_field_name = $form_state['triggering_element']['#field_name'];

    // Fill form with values from selected entity.
    if (!empty($autofill_bundle_settings[$reference_field_name]['fields'])) {
      $reference_field_parents = $form_state['triggering_element']['#parents'];
      $referenced_target_id = drupal_array_get_nested_value($form_state['values'], $reference_field_parents);
      entityreference_autofill_populate_form_by_field($referenced_target_id, $reference_field_name, $langcode, $autofill_bundle_settings[$reference_field_name], $form, $form_state);
    }
  }
  elseif (isset($form_state['entityreference_prepopulate'][$entity_type][$bundle])) {
    // Find all prepopulated reference fields in current bundle.
    foreach ($form_state['entityreference_prepopulate'][$entity_type][$bundle] as $reference_field_name => $values) {
      // Fill form with values from selected entity.
      if (!empty($autofill_bundle_settings[$reference_field_name]['fields'])) {
        // Fill for each referenced value (Better safe than sorry).
        foreach ($values as $referenced_target_id) {
          entityreference_autofill_populate_form_by_field($referenced_target_id, $reference_field_name, $langcode, $autofill_bundle_settings[$reference_field_name], $form, $form_state);
        }
      }
    }
  }
}

/**
 * Ajax callback: return prepopulated form.
 */
function entityreference_autofill_form_autofill($form, $form_state) {
  return $form;
}

/**
 * Populate other form fields with respect to this module's field settings.
 *
 * @param int $referenced_target_id
 *   id of referenced entity to fetch data from.
 * @param string $reference_field_name
 *   name of entity reference field triggering this call.
 * @param string $langcode
 *   current language.
 * @param array $autofill_field_settings
 *   module settings for $reference_field_name in current context.
 */
function entityreference_autofill_populate_form_by_field($referenced_target_id, $reference_field_name, $langcode, $autofill_field_settings, &$form, &$form_state) {

  $reference_field = $form_state['field'][$reference_field_name][$langcode];

  // Reference entity metadata.
  $referenced_entity_type = $reference_field['field']['settings']['target_type'];

  // No value, quit processing.
  if (empty($referenced_target_id)) {
    return;
  }

  // Load referenced entity.
  $referenced_entity = entity_load_single($referenced_entity_type, $referenced_target_id);

  // Populate fields with values from referenced node.
  $autofill_fields = $autofill_field_settings['fields'];
  $overwrite = $autofill_field_settings['overwrite'];
  foreach ($autofill_fields as $field_name) {
    if (isset($form[$field_name])) {
      // Consider overwrite setting.
      if (!$overwrite) {
        $field_parents = $form_state['field'][$field_name][$langcode]['array_parents'];
        $field_input = drupal_array_get_nested_value($form_state['input'], $field_parents);
        if (_entityreference_autofill_field_has_input_value($field_input)) {
          continue;
        }
      }
      // Load new value.
      $items = field_get_items($referenced_entity_type, $referenced_entity, $field_name, $langcode);
      if (!empty($items)) {
        $field = $form_state['field'][$field_name][$langcode]['field'];
        $instance = $form_state['field'][$field_name][$langcode]['instance'];
        $parents = $form['#parents'];

        // Replace field state with referenced values.
        $field_state = array(
          'field' => $field,
          'instance' => $instance,
          'items_count' => count($items),
          'array_parents' => array(),
          'errors' => array(),
        );
        field_form_set_state($parents, $field_name, $langcode, $form_state, $field_state);

        // Replace field with new defaults.
        $field_form = field_default_form($referenced_entity_type, $referenced_entity, $field, $instance, $langcode, $items, $form, $form_state);
        $form[$field_name] = reset($field_form);

        // Unset current input to use new default values in form.
        unset($form_state['input'][$field_name]);
      }
    }
  }
}

/**
 * List of widget types supported by this module.
 *
 * @return array
 *   Array of widget machine names that this module supports.
 */
function _entityreference_autofill_supported_widgets() {
  return array(
    'entityreference_autocomplete',
  );
}

/**
 * Recursive check if a field already has a set value (Experimental).
 *
 * @param string $field_input
 *   Array of field input values.
 *
 * @return bool
 *   Wheter or not the field has a value set.
 *
 * @todo Not sure how good this works, neither if there's a
 *   more efficient/clean way of doing it.
 */
function _entityreference_autofill_field_has_input_value($field_input) {
  if (is_array($field_input)) {
    foreach ($field_input as $value) {
      if (_entityreference_autofill_field_has_input_value($value)) {
        return TRUE;
      }
    }
  }
  else {
    return !empty($field_input);
  }
}

/**
 * Get settings for fields that have autofill enabled.
 *
 * @param bool $reset
 *   Boolean indicating if the settings should be generated or
 *   fetched from cache.
 *
 * @return array
 *   Multidimensional map of entityreference fields,
 *   keyed by (in order) entity type, bundle and field name.
 *   A settings entry contains:
 *   - overwrite: Boolean indicating if fields with values
 *     should be overwritten.
 *   - prepopulate: Available if the Entityreference prepopulate
 *     module is enabled for this field.
 *   - fields: Map of fields that should be filled by the module.
 */
function _entityreference_autofill_get_settings($reset = FALSE) {
  // Use cached if available.
  if (!$reset) {
    $cache = cache_get(__FUNCTION__);
    if (!empty($cache->data)) {
      return $cache->data;
    }
  }
  // Rebuild settings.
  $field_map = field_info_field_map();
  $enabled_fields = array();
  foreach ($field_map as $field_name => $field) {
    if ($field['type'] !== 'entityreference') {
      continue;
    }
    foreach ($field['bundles'] as $entity_type => $bundles) {
      foreach ($bundles as $bundle) {
        $field_info = field_info_instance($entity_type, $field_name, $bundle);
        if (isset($field_info['settings']['behaviors']['autofill'])) {
          $module_settings = $field_info['settings']['behaviors']['autofill'];
          if ($module_settings['status']) {
            // Clear unused fields from field array.
            $module_settings['fields'] = array_filter($module_settings['fields']);
            $enabled_fields[$entity_type][$bundle][$field_name] = $module_settings;
            // Reduntant, module is enabled if key exists.
            unset($module_settings['status']);
            // Entityreference prepopulate is enabled.
            if (!empty($field_info['settings']['behaviors']['prepopulate']['status'])) {
              $enabled_fields[$entity_type][$bundle][$field_name]['prepopulate'] = TRUE;
            }
          }
        }
      }
    }
  }
  cache_set(__FUNCTION__, $enabled_fields);
  return $enabled_fields;
}
