<?php
/**
 *  Implements hook_field_widget_info_alter().
 */
function entityreference_autofill_field_widget_info_alter(&$info) {
  // Add autofill settings to autocomplete widget.
  // @TODO: Support for select / radio widgets
  $info['entityreference_autocomplete']['settings'] += array(
    'autofill' => array(
      'enabled' => 0,
      'fields' => array(),
      'overwrite' => 0,
    ),
  );
}

/**
 *  Implements hook_element_form_FORM_ID_alter().
 */
function entityreference_autofill_form_field_ui_field_edit_form_alter(&$form, &$form_state) {
  $instance = $form['#instance'];
  $widget = $instance['widget'];
  
  if ($widget['type'] !== 'entityreference_autocomplete') {
    return;
  }
    
  $settings = $instance['widget']['settings'];
  $widget_form = &$form['instance']['widget']['settings'];
  
  // Add module settings to widget form    
  $widget_form['autofill'] = array(
    '#type' => 'fieldset',
    '#title' => t('Autofill settings'), 
  );
  $widget_form['autofill']['enabled'] = array(
    '#type' => 'checkbox',
    '#title' => t('Enable autofill for this field'),
    '#default_value' => $settings['autofill']['enabled'],
    '#description' => t('Select if you want to autofill form fields with values from the entity referenced in this field.'),
  );
  
  // Load available fields from instance bundle
  $entity_type = $instance['entity_type'];
  $bundle_name = $instance['bundle'];
  $bundle_info = field_info_instances($entity_type, $bundle_name);
  
  // Field target metadata
  $field_map = field_info_field_map();
  $target_type = $form['#field']['settings']['target_type'];
  $target_bundles = $form['#field']['settings']['handler_settings']['target_bundles'];
  
  // Skip autofill for the reference field
  unset($bundle_info[$instance['field_name']]);
  
  // Conditional display of sub-fields
  $enabled_states = array(
    'visible' => array(
      ':input[name="instance[widget][settings][autofill][enabled]"]' => array('checked' => TRUE),
    ),
  );
  
  // Create checkboxes options for available fields.
  $fields_options = array();
  foreach($bundle_info as $field_name => $field_info) {
    if(!empty($field_map[$field_name]['bundles'][$target_type])) {
      $available_bundles = $field_map[$field_name]['bundles'][$target_type];
      // Determine all targeted bundles that use this field
      $option_bundles = empty($target_bundles) ? $available_bundles : array_intersect($target_bundles, $available_bundles);
      if(!empty($option_bundles)) {
        $field_options[$field_name] = t(
          '@field_label (@field_name): <em>Available in bundle(s) @bundles</em>',
          array(
            '@field_label' => $field_info['label'],
            '@field_name' => $field_name,
            '@bundles' => implode(', ', $option_bundles)
          )
        );
      }
    }
  }
  
  if(!empty($field_options)) {
    $widget_form['autofill']['overwrite'] = array(
      '#type' => 'checkbox',
      // @TODO Remove warning text
      '#title' => '<strong>NOT YET IMPLEMENTED: </strong>' . t('Overwrite existing data'),
      '#default_value' => $settings['autofill']['overwrite'],
      '#description' => t('Select if you want to overwrite fields that already have values.'),
      '#states' => $enabled_states,
    );
    $widget_form['autofill']['fields'] = array(
      '#type' => 'checkboxes',
      '#title' => t('Fields'),
      '#default_value' => $settings['autofill']['fields'],
      '#options' => $field_options,
      '#description' => t('Select which fields from the referenced entity you want to load on changing the value of this field.'),
      '#states' => $enabled_states,
    );
    
    // Remove unset options from settings
    // Is #validate preferred way to do this?
    if(empty($form['#validate'])) {
      $form['#validate'] = array();
    }
    array_unshift($form['#validate'], '_entityreference_autofill_cleanup_options');
  }
  else {
    $widget_form['autofill']['nofields'] = array(
      '#markup' => '<div class="messages warning">' . t('There are no common fields between this bundle and its referenced entities. To use autofill, you need to add instances of the same fields to its referenced bundles') . '</div>',
      '#type' => 'item',
      '#states' => $enabled_states,
    );
  }
}

/**
 *  Implements hook_field_widget_form_alter().
 */
function entityreference_autofill_field_widget_form_alter(&$element, &$form_state, $context) {
  if($context['field']['type'] !== 'entityreference' ||
     $context['instance']['widget']['type'] !== 'entityreference_autocomplete' ||
     !$context['instance']['widget']['settings']['autofill']['enabled'])
  {
    return;
  }
 
  // Add ajax callback to element
  $element['target_id']['#ajax'] = array(
    'callback' => 'entityreference_autofill_form_autofill',
    // @TODO: Wrapper will be removed when ajax_replace_commands
    // are implemented in place of form replace
    'wrapper' => 'entityreference-autofill-form',
  );
}

/**
 *  Implements hook_form_alter().
 */
function entityreference_autofill_form_alter(&$form, &$form_state) {
  // Is this condition enough for checking that we're working with an entity form? 
  if(!isset($form['#entity_type'], $form['#bundle'])) {
    return;
  }
  
  // Get array of fields that have enabled autofill
  $entity_type = $form['#entity_type'];
  $bundle = $form['#bundle'];
  $autofill_settings = _entityreference_autofill_get_settings();
  
  // No autofill references in this bundle
  if(empty($autofill_settings[$entity_type][$bundle])) {
    return;
  }

  // Autofill settings for this forms associated bundle
  $autofill_bundle_settings = $autofill_settings[$entity_type][$bundle];
  
  // @TODO: Ajax replacement wrapper will be removed when ajax_replace_commands
  // are implemented instead of replacing entire form
  $form['#prefix'] = '<div id="entityreference-autofill-form">';
  $form['#suffix'] = '</div>';
     
  // Ajax call handler
  if(isset($form_state['triggering_element']['#ajax'])) {
    $reference_field_name = $form_state['triggering_element']['#field_name'];
    $reference_field = $form_state['field'][$reference_field_name][LANGUAGE_NONE];

    // If no fields are enabled for autofill / Triggering element is not autofill field
    if(empty($autofill_bundle_settings[$reference_field_name]['fields'])) {
      return;
    }
    
    // Reference entity metadata
    $referenced_entity_type = $reference_field['field']['settings']['target_type'];
    $referenced_target_id = $form_state['values'][$reference_field_name][LANGUAGE_NONE][0]['target_id'];

    // Load referenced entity
    $referenced_entity = entity_load_single($referenced_entity_type, $referenced_target_id);

    // Populate fields with values from referenced node
    // @TODO: Handle overwrite setting
    $autofill_fields = $autofill_bundle_settings[$reference_field_name]['fields'];
    foreach($autofill_fields as $field_name) {
      if(isset($form[$field_name])) {
        // Load new value(s)
        $value = $referenced_entity->{$field_name};
        if(!empty($value) && isset($form_state['values'][$field_name])) {
          // Set new value in form state
          $lang = $form[$field_name]['#language'];
          // @TODO: Make work with multiple valued fields / use better method ?
          $form_state['input'][$field_name][$lang] = $value[$lang];
          $form_state['values'][$field_name][$lang] = $value[$lang];
        }
      }
    }
    $form_state['rebuild'] = TRUE;
  }
}

/**
 *  Ajax callback: return prepopulated form
 */
function entityreference_autofill_form_autofill($form, $form_state) {
  // @TODO: Change this and form_alter to use ajax_commands for
  // each updated field instead
  return $form;
}

/**
 *  Return array of fields that have autofill enabled.
 *  @TODO: This needs to be cached, as it is called on every entity form build.
 */
function _entityreference_autofill_get_settings() {
  $field_map = field_info_field_map();
  $enabled_fields = array();
  foreach($field_map as $field_name => $field) {
    if($field['type'] !== 'entityreference') {
      continue;
    }
    foreach($field['bundles'] as $entity_type => $bundles) {
      foreach($bundles as $bundle) {
        $field_info = field_info_instance($entity_type, $field_name, $bundle);
        $field_widget = $field_info['widget'];
        if($field_widget['type'] === 'entityreference_autocomplete' &&
          $field_widget['settings']['autofill']['enabled'])
        {
          $enabled_fields[$entity_type][$bundle][$field_name] = $field_widget['settings']['autofill'];
        }
      }
    }
  }
  return $enabled_fields;  
}

/**
 *  #validate callback for field_ui_field_edit_form
 *  Clean up field array in widget settings.
 */
function _entityreference_autofill_cleanup_options(&$form, &$form_state) {
  $widget_fields = &$form_state['values']['instance']['widget']['settings']['autofill']['fields'];
  foreach($widget_fields as $field_name => $value) {
    if(!$value) {
      unset($widget_fields[$field_name]);
    };
  }
}